version: '3.8'

services:
  db:
    image: postgres:15
    container_name: workoutservice-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: workoutservice
    ports:
      - "50002:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: